### ISSUE TITLE
Rewrite "how it works" section about SLOs

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#247]
Explain
- where we get our data, for AWS and GCP
- what we do with it
- what are the limitations

**Comment by mperrien** [comment]
- explain we store the report, where and how, and why
- explain we record the SLOs-declaration manifest's state each time a report is generated, where, how, and why

**Comment by xaah** [comment]
Some initial pointers:
> where we get our data, for AWS and GCP
For AWS we query the CloudWatch API, from GCP we query the GCP Monitoring API
We request aggregated data based on the defined time windows.
>what we do with it
For Availability:
Currently a distribution of the request codes is returned by the API. We count instances of 5xx statuses.
Latency:
The get the 99th percentile for every minute within a time window. We then calculate how many minutes above or below the threshold.

> what are the limitations
Some are we need access to the API. Another is we can't currently calculate latency for all requests, only percentiles in a window.


Overall one thing to note is if we consolidate the CLI and Entity Server concepts, and any other concepts that influence this behaviour, then these details will change. Next week's discussion surrounding how to consolidate the UX for the APIs and CLI will likely be an opportunity to elucidate any queries as well.

**Comment by dmartin35** [comment]
We are currently fetching data from provider/type of resource
- GCP -> load balancer
- AWS -> api gateway
- AWS -> load balancer

Basically, when the `slo report` command is run, the CLI
- reads/loads the local manifest file 
- to have a full list all services/slos/slis defined
- for each service/slo, it averages the SLO computed value over the time period for all SLIs
- once all SLOs are computed, it sends the report to Reliably API (py) 
- finally it writes out the report in desired format to either stdout or local file

The reports are stored in the Postgres database as raw json, so that we can generate trending from history of n last reports.

The SLO-declaration of the manifest is not recorded anymore, with the revert of the slo management commands at cli level. The local manifest file is the only source of truth that can be committed on git by users, if they want to track changes to it

For availability retrieval, we fetch the error rate over the entire time period for then compute the availability as 100 - error rate. We get one value from AWS cloud watch.
Error rate is : Sum of HTTP 5xx requests / Sum all requests * 100

For latency, we fetch the 99-percentile latency for every minute over the total time period, we count the number of times the p99 is above the threshold over total number of minutes to get the value as percentage
(count p99_per_minutes > threshold ) / (total number of p99 values) * 100
